KLEI     1 return {
    override_enabled = true,
    settings_preset = "SURVIVAL_TOGETHER", -- "SURVIVAL_TOGETHER", "RELAXED", "ENDLESS", "WILDERNESS", "LIGHTS_OUT", "COMPLETE_DARKNESS", "TERRARIA", "MOD_MISSING", "SURVIVAL_TOGETHER_CLASSIC", "SURVIVAL_DEFAULT_PLUS", "DST_CAVE", "DST_CAVE_PLUS", "TERRARIA_CAVE"
    worldgen_preset = "SURVIVAL_TOGETHER", -- "SURVIVAL_TOGETHER", "RELAXED", "ENDLESS", "WILDERNESS", "LIGHTS_OUT", "COMPLETE_DARKNESS", "TERRARIA", "MOD_MISSING", "SURVIVAL_TOGETHER_CLASSIC", "SURVIVAL_DEFAULT_PLUS", "DST_CAVE", "DST_CAVE_PLUS", "TERRARIA_CAVE"
    overrides = {
        ------------------------------------- WORLDSETTINGS -------------------------------------
        -- GLOBAL
        specialevent = "default",    -- "none", "default"
        autumn = "default",          -- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
        winter = "default",          -- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
        spring = "default",          -- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
        summer = "default",          -- "noseason", "veryshortseason", "shortseason", "default", "longseason", "verylongseason", "random"
        day = "default",             -- "default", "longday", "longdusk", "longnight", "noday", "nodusk", "nonight", "onlyday", "onlydusk", "onlynight"
        spawnmode = "fixed",         -- "fixed", "scatter"
        ghostenabled = "always",     -- "none", "always"
        portalresurection = "none",  -- "none", "always"
        ghostsanitydrain = "always", -- "none", "always"
        resettime = "default",       -- "none", "slow", "default", "fast", "always"
        beefaloheat = "default",     -- "never", "rare", "default", "often", "always"
        krampus = "default",         -- "never", "rare", "default", "often", "always"

        -- EVENTS
        crow_carnival = "default",        -- "default", "enabled"
        hallowed_nights = "default",      -- "default", "enabled"
        winters_feast = "default",        -- "default", "enabled"
        year_of_the_gobbler = "default",  -- "default", "enabled"
        year_of_the_varg = "default",     -- "default", "enabled"
        year_of_the_pig = "default",      -- "default", "enabled"
        year_of_the_carrat = "default",   -- "default", "enabled"
        year_of_the_beefalo = "default",  -- "default", "enabled"
        year_of_the_catcoon = "default",  -- "default", "enabled"
        year_of_the_bunnyman = "default", -- "default", "enabled"

        -- SURVIVORS
        extrastartingitems = "default",      -- "0", "5", "default", "15", "20", "none"
        seasonalstartingitems = "default",   -- "never", "default"
        spawnprotection = "default",         -- "never", "default", "always"
        dropeverythingondespawn = "default", -- "default", "always"
        healthpenalty = "always",            -- "none", "always"
        lessdamagetaken = "none",            -- "always", "none", "more"
        temperaturedamage = "default",       -- "nonlethal", "default"
        hunger = "default",                  -- "nonlethal", "default"
        darkness = "default",                -- "nonlethal", "default"
        shadowcreatures = "default",         -- "never", "rare", "default", "often", "always"
        brightmarecreatures = "default",     -- "never", "rare", "default", "often", "always"

        -- MISC
        hounds = "default",               -- "never", "rare", "default", "often", "always"
        winterhounds = "default",         -- "never", "default"
        summerhounds = "default",         -- "never", "default"
        earthquakes = "default",          -- "never", "rare", "default", "often", "always"
        petrification = "default",        -- "none", "few", "default", "many", "max"
        wormattacks = "default",          -- "never", "rare", "default", "often", "always"
        meteorshowers = "default",        -- "never", "rare", "default", "often", "always"
        hunt = "default",                 -- "never", "rare", "default", "often", "always"
        rifts_enabled = "default",        -- "never", "default", "always"
        rifts_enabled_cave = "default",   -- "never", "default", "always"
        rifts_frequency = "default",      -- "never", "rare", "default", "often", "always"
        rifts_frequency_cave = "default", -- "never", "rare", "default", "often", "always"
        atriumgate = "default",           -- "veryslow", "slow", "default", "fast", "veryfast"
        alternatehunt = "default",        -- "never", "rare", "default", "often", "always"
        wildfires = "default",            -- "never", "rare", "default", "often", "always"
        lightning = "default",            -- "never", "rare", "default", "often", "always"
        weather = "default",              -- "never", "rare", "default", "often", "always"
        frograin = "default",             -- "never", "rare", "default", "often", "always"

        -- RESOURCES
        regrowth = "default",                   -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        cactus_regrowth = "default",            -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        lightflier_flower_regrowth = "default", -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        basicresource_regrowth = "none",        -- "none", "always"
        twiggytrees_regrowth = "default",       -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        evergreen_regrowth = "default",         -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        mushtree_moon_regrowth = "default",     -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        moon_tree_regrowth = "default",         -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        deciduoustree_regrowth = "default",     -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        palmconetree_regrowth = "default",      -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        saltstack_regrowth = "default",         -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        carrots_regrowth = "default",           -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        reeds_regrowth = "default",             -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        flowers_regrowth = "default",           -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        flower_cave_regrowth = "default",       -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        mushtree_regrowth = "default",          -- "never", "veryslow", "slow", "default", "fast", "veryfast"

        -- PORTAL_RESOURCES
        portal_spawnrate = "default",         -- "never", "rare", "default", "often", "always"
        lightcrab_portalrate = "default",     -- "never", "rare", "default", "often", "always"
        palmcone_seed_portalrate = "default", -- "never", "rare", "default", "often", "always"
        powder_monkey_portalrate = "default", -- "never", "rare", "default", "often", "always"
        monkeytail_portalrate = "default",    -- "never", "rare", "default", "often", "always"
        bananabush_portalrate = "default",    -- "never", "rare", "default", "often", "always"

        -- ANIMALS
        gnarwail = "default",         -- "never", "rare", "default", "often", "always"
        penguins = "default",         -- "never", "rare", "default", "often", "always"
        bunnymen_setting = "default", -- "never", "rare", "default", "often", "always"
        rabbits_setting = "default",  -- "never", "rare", "default", "often", "always"
        dustmoths = "default",        -- "never", "rare", "default", "often", "always"
        catcoons = "default",         -- "never", "rare", "default", "often", "always"
        perd = "default",             -- "never", "rare", "default", "often", "always"
        pigs_setting = "default",     -- "never", "rare", "default", "often", "always"
        lightfliers = "default",      -- "never", "rare", "default", "often", "always"
        rocky_setting = "default",    -- "never", "rare", "default", "often", "always"
        monkey_setting = "default",   -- "never", "rare", "default", "often", "always"
        grassgekkos = "default",      -- "never", "rare", "default", "often", "always"
        mushgnome = "default",        -- "never", "rare", "default", "often", "always"
        slurtles_setting = "default", -- "never", "rare", "default", "often", "always"
        snurtles = "default",         -- "never", "rare", "default", "often", "always"
        bees_setting = "default",     -- "never", "rare", "default", "often", "always"
        butterfly = "default",        -- "never", "rare", "default", "often", "always"
        fishschools = "default",      -- "never", "rare", "default", "often", "always"
        birds = "default",            -- "never", "rare", "default", "often", "always"
        moles_setting = "default",    -- "never", "rare", "default", "often", "always"
        wobsters = "default",         -- "never", "rare", "default", "often", "always"

        -- MONSTERS
        spider_spitter = "default",     -- "never", "rare", "default", "often", "always"
        mutated_hounds = "default",     -- "never", "default"
        pirateraids = "default",        -- "never", "rare", "default", "often", "always"
        penguins_moon = "default",      -- "never", "default"
        wasps = "default",              -- "never", "rare", "default", "often", "always"
        spider_hider = "default",       -- "never", "rare", "default", "often", "always"
        walrus_setting = "default",     -- "never", "rare", "default", "often", "always"
        hound_mounds = "default",       -- "never", "rare", "default", "often", "always"
        moon_spider = "default",        -- "never", "rare", "default", "often", "always"
        spider_dropper = "default",     -- "never", "rare", "default", "often", "always"
        mosquitos = "default",          -- "never", "rare", "default", "often", "always"
        spiders_setting = "default",    -- "never", "rare", "default", "often", "always"
        spider_warriors = "default",    -- "never", "default"
        bats_setting = "default",       -- "never", "rare", "default", "often", "always"
        molebats = "default",           -- "never", "rare", "default", "often", "always"
        nightmarecreatures = "default", -- "never", "rare", "default", "often", "always"
        frogs = "default",              -- "never", "rare", "default", "often", "always"
        lureplants = "default",         -- "never", "rare", "default", "often", "always"
        cookiecutters = "default",      -- "never", "rare", "default", "often", "always"
        merms = "default",              -- "never", "rare", "default", "often", "always"
        squid = "default",              -- "never", "rare", "default", "often", "always"
        sharks = "default",             -- "never", "rare", "default", "often", "always"

        -- GIANTS
        klaus = "default",            -- "never", "rare", "default", "often", "always"
        daywalker = "default",        -- "never", "rare", "default", "often", "always"
        crabking = "default",         -- "never", "rare", "default", "often", "always"
        eyeofterror = "default",      -- "never", "rare", "default", "often", "always"
        fruitfly = "default",         -- "never", "rare", "default", "often", "always"
        liefs = "default",            -- "never", "rare", "default", "often", "always"
        deciduousmonster = "default", -- "never", "rare", "default", "often", "always"
        toadstool = "default",        -- "never", "rare", "default", "often", "always"
        bearger = "default",          -- "never", "rare", "default", "often", "always"
        deerclops = "default",        -- "never", "rare", "default", "often", "always"
        antliontribute = "default",   -- "never", "rare", "default", "often", "always"
        beequeen = "default",         -- "never", "rare", "default", "often", "always"
        spiderqueen = "default",      -- "never", "rare", "default", "often", "always"
        malbatross = "default",       -- "never", "rare", "default", "often", "always"
        goosemoose = "default",       -- "never", "rare", "default", "often", "always"
        dragonfly = "default",        -- "never", "rare", "default", "often", "always"

        ------------------------------------- WORLDGEN -------------------------------------
        -- GLOBAL
        season_start = "default", -- "default", "winter", "spring", "summer", "autumn|spring", "winter|summer", "autumn|winter|spring|summer"

        -- MISC
        task_set = "default",          -- "default", "cave_default", "quagmire_taskset", "classic", "lavaarena_taskset"
        start_location = "default",    -- "lavaarena", "plus", "darkness", "quagmire_startlocation", "caves", "default"
        world_size = "default",        -- "small", "medium", "default", "huge"
        branching = "default",         -- "never", "least", "default", "most", "random"
        loop = "default",              -- "never", "default", "always"
        roads = "default",             -- "never", "default"
        touchstone = "default",        -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        boons = "default",             -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        cavelight = "default",         -- "never", "veryslow", "slow", "default", "fast", "veryfast"
        prefabswaps_start = "default", -- "classic", "default", "highly random"
        moon_fissure = "default",      -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        terrariumchest = "default",    -- "never", "default"
        stageplays = "default",        -- "never", "default"

        -- RESOURCES
        cactus = "default",               -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        ocean_bullkelp = "default",       -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        wormlights = "default",           -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        marshbush = "default",            -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        rock = "default",                 -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        moon_sapling = "default",         -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        moon_rock = "default",            -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        moon_tree = "default",            -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        sapling = "default",              -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        trees = "default",                -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        palmconetree = "default",         -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        ponds = "default",                -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        cave_ponds = "default",           -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        fern = "default",                 -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        meteorspawner = "default",        -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        berrybush = "default",            -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        moon_bullkelp = "default",        -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        moon_starfish = "default",        -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        ocean_seastack = "ocean_default", -- "ocean_never", "ocean_rare", "ocean_uncommon", "ocean_default", "ocean_often", "ocean_mostly", "ocean_always", "ocean_insane"
        moon_hotspring = "default",       -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        flint = "default",                -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        moon_berrybush = "default",       -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        carrot = "default",               -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        reeds = "default",                -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        flowers = "default",              -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        lichen = "default",               -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        grass = "default",                -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        flower_cave = "default",          -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        mushroom = "default",             -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        mushtree = "default",             -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        rock_ice = "default",             -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        tumbleweed = "default",           -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        banana = "default",               -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"

        -- ANIMALS
        lightninggoat = "default",    -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        bunnymen = "default",         -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        rabbits = "default",          -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        slurper = "default",          -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        moon_fruitdragon = "default", -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        pigs = "default",             -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        beefalo = "default",          -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        rocky = "default",            -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        buzzard = "default",          -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        monkey = "default",           -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        catcoon = "default",          -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        moon_carrot = "default",      -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        slurtles = "default",         -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        bees = "default",             -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        ocean_shoal = "default",      -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        moles = "default",            -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        ocean_wobsterden = "default", -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"

        -- MONSTERS
        chess = "default",                  -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        angrybees = "default",              -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        fissure = "default",                -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        worms = "default",                  -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        ocean_waterplant = "ocean_default", -- "ocean_never", "ocean_rare", "ocean_uncommon", "ocean_default", "ocean_often", "ocean_mostly", "ocean_always", "ocean_insane"
        walrus = "default",                 -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        merm = "default",                   -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        houndmound = "default",             -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        moon_spiders = "default",           -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        cave_spiders = "default",           -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        spiders = "default",                -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        bats = "default",                   -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        tentacles = "default",              -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
        tallbirds = "default",              -- "never", "rare", "uncommon", "default", "often", "mostly", "always", "insane"
    },
}
